

/*TABELA DE USO GERAL - CONTROLE DE VERSÃO DE APLICAÇÃO - UGETBLCVA*/
CREATE TABLE IF NOT EXISTS `UGETBLCVA` (
  `CVACOD` int(11) NOT NULL AUTO_INCREMENT,
  `CVAVERSAO` varchar(50) NOT NULL,
  `CVADATCADASTRO` DATETIME NOT NULL,
  `CVAUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`CVACOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*TABELA DE USO GERAL - CONTROLE DE VERSÃO DE BANCO - UGETBLCVB*/
CREATE TABLE IF NOT EXISTS `UGETBLCVB` (
  `CVBCOD` int(11) NOT NULL AUTO_INCREMENT,
  `CVBVERSAO` varchar(50) NOT NULL,
  `CVBDATCADASTRO` DATETIME NOT NULL,
  `CVBUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`CVBCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*TABELA DE STATUS CARRO*/
CREATE TABLE IF NOT EXISTS `KGCTBLSTACAR` (
  `STACOD` int(11) NOT NULL AUTO_INCREMENT,
  `STADESCRICAO` varchar(50) NOT NULL,
  `STADATCADASTRO` DATETIME NOT NULL,
  `STAUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`STACOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*TABELA DE TIPOS DE CAMBIO*/
CREATE TABLE IF NOT EXISTS `KGCTBLCAM` (
  `CAMCOD` int(11) NOT NULL AUTO_INCREMENT,
  `CAMDESCRICAO` varchar(50) NOT NULL,
  `CAMDATCADASTRO` DATETIME NOT NULL,
  `CAMUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`CAMCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*TABELA DE TIPOS DE COMBUSTIVEL*/
CREATE TABLE IF NOT EXISTS `KGCTBLCOM` (
  `COMCOD` int(11) NOT NULL AUTO_INCREMENT,
  `COMDESCRICAO` varchar(50) NOT NULL,
  `COMDATCADASTRO` DATETIME NOT NULL,
  `COMUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`COMCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*TABELA DE CORES DOS CARROS*/
CREATE TABLE IF NOT EXISTS `KGCTBLCOR` (
  `CORCOD` int(11) NOT NULL AUTO_INCREMENT,
  `CORDESCRICAO` varchar(50) NOT NULL,
  `CORCODHEXADECIMAL` varchar(7) NOT NULL,
  `CORDATCADASTRO` DATETIME NOT NULL,
  `CORUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`CORCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



/*TABELA DE CONTATOS REALIZADOS VIA SITE*/
CREATE TABLE IF NOT EXISTS `KGCTBLCON` (
  `CONCOD` int(11) NOT NULL AUTO_INCREMENT,
  `CONNOME` varchar(255) NOT NULL,
  `CONEMAIL` varchar(255) NOT NULL,
  `CONASSUNTO` varchar(255) NOT NULL,
  `CONMENSAGEM` varchar(1000) NOT NULL,
  PRIMARY KEY (`CONCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*TABELA DE MARCAS*/
CREATE TABLE IF NOT EXISTS `KGCTBLMAR` (
  `MARCOD` int(11) NOT NULL AUTO_INCREMENT,
  `MARDESCRICAO` varchar(50) NOT NULL,
  `MARDATCADASTRO` DATETIME NOT NULL,
  `MARUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`MARCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*INSERINDO REGISTROS NA TABELA DE MARCA*/
INSERT INTO `KGCTBLMAR` (`MARCOD`, `MARDESCRICAO`,`MARDATCADASTRO`,`MARUSER`) VALUES
(1, 'Fiat', CURRENT_TIMESTAMP, 'ADMIN'),
(2, 'Audi', CURRENT_TIMESTAMP, 'ADMIN'),
(3, 'BMW', CURRENT_TIMESTAMP, 'ADMIN'),
(4, 'Chevrolet', CURRENT_TIMESTAMP, 'ADMIN'),
(5, 'Citroen', CURRENT_TIMESTAMP, 'ADMIN'),
(6, 'Ford', CURRENT_TIMESTAMP, 'ADMIN'),
(7, 'Honda', CURRENT_TIMESTAMP, 'ADMIN'),
(8, 'Hyundai', CURRENT_TIMESTAMP, 'ADMIN'),
(9, 'Jeep', CURRENT_TIMESTAMP, 'ADMIN'),
(10, 'Mitsubishi', CURRENT_TIMESTAMP, 'ADMIN'),
(11, 'Peugeot', CURRENT_TIMESTAMP, 'ADMIN'),
(12, 'Renault', CURRENT_TIMESTAMP, 'ADMIN'),
(13, 'Suzuki', CURRENT_TIMESTAMP, 'ADMIN'),
(14, 'Toyota', CURRENT_TIMESTAMP, 'ADMIN'),
(15, 'Volkswagem', CURRENT_TIMESTAMP, 'ADMIN'),
(17, 'Outro', CURRENT_TIMESTAMP, 'ADMIN');

/*TABELA DE MODELOS*/
CREATE TABLE IF NOT EXISTS `KGCTBLMOD` (
  `MODCOD` int(11) NOT NULL AUTO_INCREMENT,
  `MODDESCRICAO` varchar(50) NOT NULL,
  `MODCODMARCA` INT(11) NOT NULL,
  `MODDATCADASTRO` DATETIME NOT NULL,
  `MODUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`MODCOD`),
  KEY `MODCODMARCA` (`MODCODMARCA`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*TABELA DE CONTATOS CADASTRADOS PARA RECEBER ANUNCIO*/
CREATE TABLE IF NOT EXISTS `KGCTBLRECANU` (
  `RECCOD` int(11) NOT NULL AUTO_INCREMENT,
  `RECEMAIL` varchar(255) NOT NULL,
  PRIMARY KEY (`RECCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*TABELA DE TIPO DE USUARIOS*/
CREATE TABLE IF NOT EXISTS `KGCTBLTIPUSU` (
  `TIPCOD` int(11) NOT NULL AUTO_INCREMENT,
  `TIPDESCRICAO` varchar(50) NOT NULL,
  `TIPDATCADASTRO` DATETIME NOT NULL,
  `TIPUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`TIPCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*TABELA DE USUARIOS*/
CREATE TABLE IF NOT EXISTS `KGCTBLUSU` (
  `USUCOD` int(11) NOT NULL AUTO_INCREMENT,
  `USUNOME` varchar(40) NOT NULL,
  `USUEMAIL` varchar(50) NULL,
  `USUSENHA` varchar(50) NULL,
  `USUCODTIPO` INT(11) NULL,
  `USUUSUARIO` varchar(50) NOT NULL,
  `USUDATCADASTRO` DATETIME NOT NULL,
  `USUUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`USUCOD`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*TABELA DE PUBLICIDADES*/
CREATE TABLE KGCTBLPUB (
  `PUBCOD` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `PUBTITULO` VARCHAR(100) NOT NULL,
  `PUBIMG` VARCHAR(255) NOT NULL,
  `PUBEMPRESA` VARCHAR(255) NOT NULL,
  `PUBDATCADASTRO` DATETIME NOT NULL,
  `PUBUSER` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PUBCOD`)
)
ENGINE = InnoDB
COMMENT = 'TABELA DE PUBLICIDADES';

/*TABELA DE SOLICITAÇÃO DE ANUNCIOS*/
CREATE TABLE `kingcar`.`KGCTBLSOLANU` (
  `SOLCOD` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `SOLANUNCIANTE` VARCHAR(255) NOT NULL,
  `SOLCODMARCA` INTEGER UNSIGNED NOT NULL,
  `SOLCODMODELO` INTEGER UNSIGNED NOT NULL,
  `SOLANO` VARCHAR(4) NOT NULL,
  `SOLPRECO` DOUBLE(10,2) NOT NULL,
  `SOLDATCADASTRO` DATETIME NOT NULL,
  `SOLUSER` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SOLCOD`)
)
ENGINE = InnoDB
COMMENT = 'TABELA DE SOLICITAÇÃO DE ANUNCIOS';

/*TABELA DE CARROS ANUNCIADOS*/
CREATE TABLE  KGCTBLCAR (
  `CARCOD` int(11) NOT NULL AUTO_INCREMENT,
  `CARNOME` varchar(50) NOT NULL,
  `CARCODMARCA` int(11) NOT NULL,
  `CARCODMODELO` int(11) NOT NULL,
  `CARPRECO` double(9,2) NOT NULL,
  `CARANO` varchar(4) NOT NULL,
  `CARFOTO` varchar(255) NOT NULL,
  `CARCODSTATUS` int(11) NOT NULL,
  `CARKM` double(10,2) NOT NULL,
  `CARCODCAMBIO` int(11) NOT NULL,
  `CARPORTAS` int(1) NOT NULL,
  `CARCODCOMBUSTIVEL` int(11) NOT NULL,
  `CARCODCOR` int(11) NOT NULL,
  `CARPLACA` varchar(8) NOT NULL,
  `CARTROCA` varchar(1) NOT NULL,
  `CARDESTAQUE` varchar(1) NOT NULL,
  `CARDATCADASTRO` datetime NOT NULL,
  `CARUSER` varchar(50) NOT NULL,
  PRIMARY KEY (`CARCOD`),
  KEY `CARCODMARCA` (`CARCODMARCA`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



/*APÓS TODOS OS SCRIPTS DESTE ARQUIVO SEREM RODADOS, SERÁ INCLUIDO UM REGISTRO NA TABELA UGETBLCVB INFORMANDO A VERSÃO DO BANCO*/
/*INSERINDO REGISTROS NA TABELA DE MARCA*/
INSERT INTO `UGETBLCVB` (CVBVERSAO, CVBDATCADASTRO, CVBUSER) VALUES
('001', CURRENT_TIMESTAMP, 'SCRIPT_BANCO');

